media: src/static
content: 
  - name: posts
    label: Posts
    type: collection
    path: src/blog
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date }
      - { name: description, label: Description, type: string, options: { maxlength: 150 } }
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }

  